apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-loiv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-loiv@sha256:853bc7b3f9c2a83fcaf2608c579f59c3f1951404be8b39e38aa98f5f8de63050
        name: my-nodejs
        resources: {}
status: {}
